### ISSUE TITLE
Expired row deletion query should use .between instead of filter

### ISSUE THREAD

**Issue by deontologician** [codedmart/catbox-rethinkdb#3]
Right now it isn't using the 'expiresAt' index since it's using a filter (which can't take advantage of indexes)

this line:https://github.com/codedmart/catbox-rethinkdb/blob/master/lib/index.js#L39

should become something like:

``` js
this.table
    .between(RethinkDB.minval(), RethinkDB.now(), {index: 'expiresAt'})
    .delete()
    .run(this.client);
```

**Comment by codedmart** [comment]
@deontologician Great I will set some time aside for this today. Thanks!
