### ISSUE TITLE
Replace query should use .get() to use the primary index

### ISSUE THREAD

**Issue by deontologician** [codedmart/catbox-rethinkdb#4]
Right now this query:

``` js
this.table.replace(record).run(this.client, ...
```

(from [here](https://github.com/codedmart/catbox-rethinkdb/blob/master/lib/index.js#L201))

is doing a full table scan. It tries to replace every row, and fails on all of them except for the target document. This is actually worse than a normal table scan because it won't quit when it finds the correct document, it keeps trying to replace all of the rest of the documents in the table (and will fail on them)

The query should be something like:

``` js
this.table.get(record.id).replace(record).run(this.client, ...
```

**Comment by codedmart** [comment]
@deontologician Great I will set some time aside for this today. Thanks!
